name: Build LaTeX & upload handout
on:
  push:
    branches:
      - advanced_course_II_ultraprecision_engineering
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4

    - name: Compile handout
      uses: xu-cheng/latex-action@v3
      env:
        TZ: "Europe/Zurich"
      with:
        root_file: |
          XRayMicroTomography.Handout.tex

    - name: Verify generated PDF
      run: |
        file XRayMicroTomography.Handout.pdf | grep -q ' PDF '

    - name: Deploy handout PDF to gh-pages branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        destination_dir: .
        keep_files: true
        commit_message: "Deploy new version of presentation handout to gh-pages"
